bankingproject/bankingapp/urls.py
from django.urls import path
from . import views
from users import views as user_views
app_name = 'bankingapp'
urlpatterns = [
    path('', views.index, name='index'),


    path('register_success/', views.register_success, name='register_success'),
    path('member/add/', views.create_view, name='add'),

    path('member/ajax/load-branches/', views.load_branches, name='ajax_load_branches'),  # AJAX
    path('user_created/',views.user_created,name='user_created'),

]

bankingproject/bankingproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankingapp.urls', namespace='bankingapp')),
    path('users/',include('users.urls',namespace='users')),
    path('credentials/',include('credentials.urls',namespace='credentials')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingproject/users/urls.py
from . import views
from django.urls import path

from users import views as user_views
app_name="users"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='login'),
    path('signout/', views.signout, name='logout'),
    path('register',views.register,name='register')

]

bankingproject/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    # if created:
    #     Profile.objects.create(user=instance)
    # instance.profile.save()

    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        Profile.objects.create(user=instance)

bankingproject/users/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.views import View

from bankingapp.forms import MemberCreationForm, RegisterForm
from bankingapp.models import Register


def register_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/')
        else:
            form = RegisterForm()
            context = {'form': form}
            return render(request, 'users/signup.html', context)

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            # return redirect('users/user_created.html')

    return render(request, 'users/signup.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            return render(request, 'user_created.html')

        else:
            return render(request, 'users/signup.html', {'form': form})

    else:
        form = UserCreationForm()
        return render(request, 'users/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
       # login(request,user)
        if user is not None:
            print("***"+user.username)

            if Register.objects.filter(user=user.username).exists():
                return render(request, "users/user_already_registered.html")
            else:
                form = MemberCreationForm()
                login(request, user)
                # return redirect('/')
                return render(request, 'home.html', {'form': form})


        else:
            messages.info(request, "Invalid username or password")
            form = AuthenticationForm()
            return render(request, 'users/signin.html', {'form': form})

    else:
        form = AuthenticationForm()
        return render(request, 'users/signin.html', {'form': form})


def age(self):
    return int((datetime.now().date() - self.birth_date).days / 365.25)


def register(request):
    return render(request, "home.html")


def base_cv(request):
    con = {'cvs': Register.objects.all()}
    return render(request, 'users/signin.html', con)


def signout(request):
    logout(request)
    return redirect('/')

bankingproject/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>User Authentication </title>

    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

bankingproject/templates/users/home.html
{% extends 'users/base.html' %}

{% block style %}
    <style>
        h1 {
            text-align: center;
        }
        a {
            display: inline-block;
            background: #313030;
            color: #FFF;
            border: 0;
            border-radius: 4px;
            text-align: center;
            padding: 20px 30px;
            line-height: 1;
            text-decoration: none;
        }
        a:hover {
          background: #c7c5c5;
          color: #313030;
        }
        .a2 {
            margin-left: 1em;
        }
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 200px;
            border: 3px solid #313030;
        }
    </style>
{% endblock style %}

{% block content %}
    <br>
    {% if user.is_authenticated %}
        <div class="alert alert-success" role="alert">
            <h1>Welcome {{ user.username }}!</h1>
        </div>
    {% else %}
        <div class="alert alert-success" role="alert">
            <h1>Welcome to Authentication System!</h1>
        </div>
    {% endif %}
    <br>
    <div class="center">
        {% if user.is_authenticated %}

            <a class="a2" href="{% url 'logout' %} ">Logout</a>
        {% else %}
            <a class="a1" href="{% url  'users:signup' %}">Sign Up</a>
            <a class="a2" href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
{% endblock content %}

bankingproject/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
  <br>
  <div class="alert alert-primary" role="alert">
    <h2 style="text-align: center;">Login </h2>
  </div>
  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    <p>
    {{ form.as_p }}
      <button type="submit">Login</button></p>
  </form>
New User??<a href="{% url 'users:signup' %}">Sign up here </a>

{% endblock %}

bankingproject/templates/users/logout.html
{% extends 'users/base.html' %}

{% block content %}
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out!</h2>
    </div>

    <h3>Login again?</h3>
    <a href="{% url 'login' %}">---> Login</a> <br>
    <a href="{% url 'bankingapp:index' %}"><--- Or go back to home.</a>
{% endblock content %}

bankingproject/templates/users/register.html
<h3>Register here </h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <p>{{ field.label }}: <br> {{ field }}</p>

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit">Register</button>
</form>

bankingproject/templates/users/signin.html
{% load static %}
<html>

<head>
    <title>User Authentication System</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <style>
    body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
    }

    main {
      flex: 1 0 auto;
    }

    body {
      background: #fff;
    }

    .input-field input[type=date]:focus + label,
    .input-field input[type=text]:focus + label,
    .input-field input[type=email]:focus + label,
    .input-field input[type=password]:focus + label {
      color: #e91e63;
    }

    .input-field input[type=date]:focus,
    .input-field input[type=text]:focus,
    .input-field input[type=email]:focus,
    .input-field input[type=password]:focus {
      border-bottom: 2px solid #e91e63;
      box-shadow: none;
    }
  </style>
</head>

<body>
  <div class="section"></div>
  <main>
    <center>
      <img class="responsive-img" style="width: 250px;" src="{% static 'img/abc_bank.png' %}" alt="load image" />
      <div class="section"></div>

      <h5 class="indigo-text">Please, login into your account</h5>
      <div class="section"></div>

      <div class="container">
        <div class="z-depth-1 grey lighten-4 row" style="display: inline-block; padding: 32px 48px 0px 48px; border: 1px solid #EEE;">

          <form class="col s12" method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
            <div class='row'>
              <div class='col s12'>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='text' name='username' id='username' />
                <label for='username'>Enter your username</label>
              </div>
            </div>

            <div class='row'>
              <div class='input-field col s12'>
                <input class='validate' type='password' name='password' id='password' />
                <label for='password'>Enter your password</label>
              </div>

            </div>

            <br />
            <center>
              <div class='row'>
                <button type='submit' name='btn_login' class='col s12 btn btn-large waves-effect indigo'>Login</button>
              </div>
            </center>
          </form>
        </div>
      </div>
      New user?<a href="{% url  'users:signup' %}">Create account</a>|
		<a href="{% url  'bankingapp:index' %}">Back To Home</a>
    </center>

    <div class="section"></div>
    <div class="section"></div>
  </main>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>

</html>

bankingproject/templates/users/signup.html
{% extends 'users/base.html' %}
{% block content %}
<br>
  <div class="alert alert-primary" role="alert">
    <h2 style="text-align: center;">Sign Up  Here</h2>
  </div>
<form method ='post'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value = "Submit">
</form>

<h5>Already Have an Account??
    <a href = "{% url 'users:login' %}">Sign In Here</a></h5>

{% endblock %}

bankingproject/templates/users/user_already_registered.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>User already Registered!!!
<a class="a2" href="{%url 'bankingapp:index'%}">Back To Home</a>
</h2>
</body>
</html>