bankingproject/bankingapp/urls.py
from django.urls import path
from . import views
from users import views as user_views
app_name = 'bankingapp'
urlpatterns = [
    path('', views.index, name='index'),


    path('register_success/', views.register_success, name='register_success'),
    path('member/add/', views.create_view, name='add'),

    path('member/ajax/load-branches/', views.load_branches, name='ajax_load_branches'),  # AJAX
    path('user_created/',views.user_created,name='user_created'),

]

bankingproject/bankingproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bankingapp.urls', namespace='bankingapp')),
    path('users/',include('users.urls',namespace='users')),
    path('credentials/',include('credentials.urls',namespace='credentials')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingproject/users/urls.py
from . import views
from django.urls import path

from users import views as user_views
app_name="users"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='login'),
    path('signout/', views.signout, name='logout'),
    path('register',views.register,name='register')

]

bankingproject/bankingapp/models.py
from datetime import datetime

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class District(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name


class Register(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female')
    )
    ACCOUNT_CHOICES = (
        ('C', 'Current'),
        ('S', 'Savings')
    )

   # username = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True,null=True,default="",editable=False)
   #  current_user = models.ForeignKey(
   #      settings.AUTH_USER_MODEL,
   #      on_delete=models.CASCADE,
   #      to_field='username'
   #  )
    #user = models.CharField(max_length=100,null=True)
    user = models.CharField(max_length=100,null=True)
    name = models.CharField(max_length=100)
    birthdate = models.DateField(default=datetime.now, null=True)
    age = models.CharField(max_length=3, blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=128)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    address = models.TextField(max_length=100)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    account = models.CharField(choices=ACCOUNT_CHOICES, max_length=128)
    material_choices = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return str(self.user)

bankingproject/templates/base.html
{% load static %}

{% block style %}
    <style>
        h1 {
            text-align: center;
        }
        a {
            display: inline-block;
            background: #313030;
            color: #FFF;
            border: 0;
            border-radius: 4px;
            text-align: center;
            padding: 20px 30px;
            line-height: 1;
            text-decoration: none;
        }
        a:hover {
          background: #c7c5c5;
          color: #313030;
        }
        .a2 {
            margin-left: 1em;
        }
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 200px;
            border: 3px solid #313030;
        }
    </style>
{% endblock style %}
<head>
   <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js">

    </script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<script>$('.dateinput').datepicker({ format: 'yyyy-mm-dd' });</script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title></head>

    <body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}

{% block body %}

{% endblock %}
</div>
{% include 'footer.html' %}
</body>
</html>

bankingproject/templates/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

bankingproject/templates/district.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if district %}
        {{ District.name }}
    {% else %}
        Welcome
    {% endif %}
{% endblock %}

{% block title %}
     {% if district %}
        {{ District.name }}
    {% else %}

        ABC Bank
    {% endif %}
{% endblock %}

{% block content %}
    {% if district %}
        <div>
            <div>
                <p><a href="">Branches</a></p>
            </div>
        </div>

    {% endif %}
{% endblock %}

bankingproject/templates/email.html
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<title></title>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900');
		</style>
	</head>
	<body style="background: #f5f8fa;font-family: 'Roboto', sans-serif;">
		<div style="width: 90%;max-width:600px;margin: 20px auto;background: #ffffff;">
			<section style="margin: 0 15px;color:#425b76;">
				<h2 style="margin: 40px 0 27px 0;text-align: center;">Thank you to registration</h2>
				<hr style="border:0;border-top: 1px solid rgba(66,91,118,0.3);max-width: 50%">
				<p style="font-size:15.5px;font-weight: bold;margin:40px 20px 15px 20px;">Hi {{username}}, we have received your details and will process soon.</p>
			</section>
		</div>
	</body>
</html>

bankingproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; ABC tech Ltd.All rights Reserved</p>
</div>

bankingproject/templates/header.html
{% load static %}
<header>
<center><br>
<img src="{% static 'img/logo.png' %}" alt="load image" height="430" width="100%">

  </center>
</header>
    <br>

    <div class="right">
        {% if user.is_authenticated %}
                    <h3 style="text-align:right;color:blue;">Welcome {{ user.username }}!
                        <a class="a2" href="{% url 'users:logout' %} ">Logout</a></h3>

        {% else %}


        <h3 style="text-align:right;">
         <a class="a2" href="{% url 'users:login' %}">Login</a></h3>
    </div>
        {% endif %}
    </div>

bankingproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<div class="container">
    <div class="card">
        <div class="card-header alert alert-primary">

 <h3><center>REGISTRATION FORM</center></h3>
        </div>
        <div class="card-body" >
            <form method="post" action="{% url 'bankingapp:add' %}" enctype="multipart/form-data" id="MemberForm" data-branches-url="{% url 'bankingapp:ajax_load_branches' %}" class="form-horizontal" role="form">
                {% csrf_token %}

                {% crispy form %}

                <input type="submit" value="Submit" class="btn btn-info">
            </form>
        </div>
      </div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#MemberForm").attr("data-branches-url");  // get the url of the `load_branches` view
        const districtId = $(this).val();  // get the selected District ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /members/ajax/load-branches/ )
            data: {
                'district_id': districtId       // GET parameters
            },
            success: function (data) {
                $("#id_branch").html(data);
            }
     });

    });
</script>
<!-- Include Required Prerequisites -->
<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />

<!-- Include Date Range Picker -->
<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />


  <script type="text/javascript">
         $(function() {
            $('input[name="birthdate"]').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true
            },
            function(start, end, label) {
                var years = moment().diff(start, 'years');
               // alert(years);
                $("#id_age").val(years);

            });
        });
</script>
{% endblock %}

bankingproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
 <div class="container">
    <div class="row">

        <img class="my_image my_image_padding" src="{% static 'img/banner.png'  %}" alt="" width="1250">

    </div>


</div>

      {% endblock %}

bankingproject/templates/login_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post"><input type="submit"></form>


</body>
</html>

bankingproject/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

</head>
<body>

<div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-light bg-light">

        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--                <li class="nav-item"><a class="nav-link" href="{% url 'bankingapp:index' %}">Home</a></li>-->

                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a href="{% url 'users:login' %} " class="nav-link" data-target="#exampleModalCenter" data-toggle="modal">Register</a></li>
                {% else %}
                <a href="#" class="nav-link" data-target="#exampleModalCenter" data-toggle="modal">Register</a></li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Branches</a>
                    <div class="dropdown-menu">
                         {% for dist in links %}
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/{{ dist.name }}" target="_blank">{{dist.name}}</a>
                   {%  endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Instructions</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3> To proceed with the Registration process, do the following</h3><br>
               <h5>&#x2022; Create a username and password</h5>
                <h5>&#x2022; After creating username and password, you will be directed to Registration Page</h5>
                <h5>&#x2022; Fill up the Registration form and submit </h5><br>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-primary" onclick="location.href='{% url 'users:login' %}'">Login</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
</body>
</html>

bankingproject/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<div class="content-section col-md-8 col-md-offset-2" >
  <form method="POST" style="border: 1px solid black; margin: 4%; padding:10%; border-radius:1%;">
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy}}
    </fieldset>
    <center>
      <button style="background: black; padding:2%; font-size: 2rem; color:white;" class="btn btn-outline-info" type="submit"><span class="glyphicon glyphicon-check"></span> &nbsp; sign up</button>
    </center>
    <br />
    <sub><a href="{% url 'bankingapp:login' %}" style="text-decoration: none; color: blue; padding:3%; cursor:pointer;">Already have an account ?</a></sub>
  </form>
</div>
{% endblock %}

bankingproject/templates/register_form.html
{% extends 'base.html' %}

{% load static %}
{% block body %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <script type='text/javascript' src="{%  static 'js/jquery.min.js' %}"></script><!-- see the change here -->

<form class="d-flex" action="{% url 'bankingapp:reg_add' %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class ="container">
        <div class="overflow-auto" style="overflow:scroll">
    <center><b><u>REGISTRATION FORM</u></b></center> <br>
    Name
<input type="text" name="name" size="20"/> <br><br>
 Date of Birth
<input type="date" name="dob" > <br><br>
Age:
<input type="text" name="age" size="3"/> <br><br>

Gender :

<input type="radio" name="gender"/> Male
<input type="radio" name="gender"/> Female
<input type="radio" name="gender"/> Other
<br>

<br>

Phone :


<input type="text" name="phone" size="10"/> <br><br>
     Email:
<input type="email" name="email" size="25"/> <br><br>
Address
<br>
<textarea cols="80" rows="5" value="address">
</textarea>
<br><br>
        District
<select id="distddl" name="distddl" >
            <option disabled selected="true">--Select District--</option>
            {% for d in distdata  %}
            <option value="{{ d.name }}">{{ d.name }}</option>
            {% endfor %}
        </select>

            Branch
  <select id="branchddl" name="branchddl">
                        <option disabled selected="true">--Select Branch--</option>

                        {% for b in branchdata  %}

            <option value="{{ b.district }}">{{ b.name }}</option>
            {% endfor %}

  </select>

<br><br>
    Account Type

<select name="acc" id="acc">
  <option value="savings">Savings</option>
  <option value="current">Current</option>

</select>
<br><br>
    Materials provided
<input type="checkbox" id="debit" name="material">Debit Card
    <input type="checkbox" id="credit" name="material">Credit Card
    <input type="checkbox" id="cheque" name="material">Cheque Book <br><br>
<input type="submit" name="register" value="Register">
        </div></div></form>
{% endblock %}

<script type = "text/javascript">
    $(document).ready(function(){
        $('#distddl').on('change',function(){

            $options=$('#branchddl').find('option');
            alert($(this).val(););
            $('#branchddl').html($options.filter('[value="'+ this.value  +'"]'));
        });
    });
</script>

bankingproject/templates/register_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
User created successfully....
<a href="{% url 'bankingapp:index' %}">Back to Home</a>
</body>
</html>

bankingproject/templates/user_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Thank you for creating an account.... Please<a class="a2" href="{%url 'users:login'%}"> Register Here</a>|
<a class="a2" href="{%url 'bankingapp:index'%}">Back To Home</a>
</h2>
</body>
</html>